name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build --argstr mode webapp
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: result
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-build --argstr mode library
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: result
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}